language: node_js
services:
  - redis-server
node_js:
- "10"
cache:
  directories:
  - "node_modules"
script:
- npm test
deploy:
  provider: npm
  email: "$NPM_EMAIL"
  token: "$NPM_TOKEN"
  skip_cleanup: true
  on:
    node: "10"
    tags: true
